/*
 * odo dev
 *
 * API interface for 'odo dev'
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApplyCommand struct {
	Component string `json:"component,omitempty"`
}

// AssertApplyCommandRequired checks if the required fields are not zero-ed
func AssertApplyCommandRequired(obj ApplyCommand) error {
	return nil
}

// AssertRecurseApplyCommandRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ApplyCommand (e.g. [][]ApplyCommand), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseApplyCommandRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aApplyCommand, ok := obj.(ApplyCommand)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertApplyCommandRequired(aApplyCommand)
	})
}
