/*
 * odo dev
 *
 * API interface for 'odo dev'
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DevstateDevfilePutRequest struct {
	Content string `json:"content"`
}

// AssertDevstateDevfilePutRequestRequired checks if the required fields are not zero-ed
func AssertDevstateDevfilePutRequestRequired(obj DevstateDevfilePutRequest) error {
	elements := map[string]interface{}{
		"content": obj.Content,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseDevstateDevfilePutRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DevstateDevfilePutRequest (e.g. [][]DevstateDevfilePutRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDevstateDevfilePutRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDevstateDevfilePutRequest, ok := obj.(DevstateDevfilePutRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDevstateDevfilePutRequestRequired(aDevstateDevfilePutRequest)
	})
}
