/*
 * odo dev
 *
 * API interface for 'odo dev'
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DevstateMetadataPut200Response struct {

	// Content of the Devfile
	Component map[string]interface{} `json:"component,omitempty"`
}

// AssertDevstateMetadataPut200ResponseRequired checks if the required fields are not zero-ed
func AssertDevstateMetadataPut200ResponseRequired(obj DevstateMetadataPut200Response) error {
	return nil
}

// AssertRecurseDevstateMetadataPut200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DevstateMetadataPut200Response (e.g. [][]DevstateMetadataPut200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDevstateMetadataPut200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDevstateMetadataPut200Response, ok := obj.(DevstateMetadataPut200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDevstateMetadataPut200ResponseRequired(aDevstateMetadataPut200Response)
	})
}
