/*
 * odo dev
 *
 * API interface for 'odo dev'
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DevstateVolumePostRequest struct {

	// Name of the volume
	Name string `json:"name,omitempty"`

	// Minimal size of the volume
	Size string `json:"size,omitempty"`

	// True if the Volume is Ephemeral
	Ephemeral bool `json:"ephemeral,omitempty"`
}

// AssertDevstateVolumePostRequestRequired checks if the required fields are not zero-ed
func AssertDevstateVolumePostRequestRequired(obj DevstateVolumePostRequest) error {
	return nil
}

// AssertRecurseDevstateVolumePostRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DevstateVolumePostRequest (e.g. [][]DevstateVolumePostRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDevstateVolumePostRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDevstateVolumePostRequest, ok := obj.(DevstateVolumePostRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDevstateVolumePostRequestRequired(aDevstateVolumePostRequest)
	})
}
