/*
 * odo dev
 *
 * API interface for 'odo dev'
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NotificationsGet200ResponseInner struct {
	Timestamp int64 `json:"timestamp,omitempty"`

	Event string `json:"event,omitempty"`

	Data DevfileUpdatedNotificationData `json:"data,omitempty"`
}

// AssertNotificationsGet200ResponseInnerRequired checks if the required fields are not zero-ed
func AssertNotificationsGet200ResponseInnerRequired(obj NotificationsGet200ResponseInner) error {
	if err := AssertDevfileUpdatedNotificationDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertRecurseNotificationsGet200ResponseInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NotificationsGet200ResponseInner (e.g. [][]NotificationsGet200ResponseInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNotificationsGet200ResponseInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNotificationsGet200ResponseInner, ok := obj.(NotificationsGet200ResponseInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNotificationsGet200ResponseInnerRequired(aNotificationsGet200ResponseInner)
	})
}
