/*
 * odo dev
 *
 * API interface for 'odo dev'
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DevfileUpdatedNotificationData struct {
	Path string `json:"path,omitempty"`
}

// AssertDevfileUpdatedNotificationDataRequired checks if the required fields are not zero-ed
func AssertDevfileUpdatedNotificationDataRequired(obj DevfileUpdatedNotificationData) error {
	return nil
}

// AssertRecurseDevfileUpdatedNotificationDataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DevfileUpdatedNotificationData (e.g. [][]DevfileUpdatedNotificationData), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDevfileUpdatedNotificationDataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDevfileUpdatedNotificationData, ok := obj.(DevfileUpdatedNotificationData)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDevfileUpdatedNotificationDataRequired(aDevfileUpdatedNotificationData)
	})
}
