/*
 * odo dev
 *
 * API interface for 'odo dev'
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
)

type InstanceGet200Response struct {

	// Directory on which this 'odo dev' instance is running
	ComponentDirectory string `json:"componentDirectory,omitempty"`

	// PID of the this 'odo dev' instance.
	Pid int32 `json:"pid,omitempty"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *InstanceGet200Response) UnmarshalJSON(data []byte) error {

	type Alias InstanceGet200Response // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertInstanceGet200ResponseRequired checks if the required fields are not zero-ed
func AssertInstanceGet200ResponseRequired(obj InstanceGet200Response) error {
	return nil
}

// AssertInstanceGet200ResponseConstraints checks if the values respects the defined constraints
func AssertInstanceGet200ResponseConstraints(obj InstanceGet200Response) error {
	return nil
}
