/*
 * odo dev
 *
 * API interface for 'odo dev'
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DevstateApplyCommandCommandNamePatchRequest struct {
	Component string `json:"component,omitempty"`
}

// AssertDevstateApplyCommandCommandNamePatchRequestRequired checks if the required fields are not zero-ed
func AssertDevstateApplyCommandCommandNamePatchRequestRequired(obj DevstateApplyCommandCommandNamePatchRequest) error {
	return nil
}

// AssertRecurseDevstateApplyCommandCommandNamePatchRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DevstateApplyCommandCommandNamePatchRequest (e.g. [][]DevstateApplyCommandCommandNamePatchRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDevstateApplyCommandCommandNamePatchRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDevstateApplyCommandCommandNamePatchRequest, ok := obj.(DevstateApplyCommandCommandNamePatchRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDevstateApplyCommandCommandNamePatchRequestRequired(aDevstateApplyCommandCommandNamePatchRequest)
	})
}
