/*
 * odo dev
 *
 * API interface for 'odo dev'
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DevfileContent struct {

	// Content of the Devfile
	Component map[string]interface{} `json:"component,omitempty"`
}

// AssertDevfileContentRequired checks if the required fields are not zero-ed
func AssertDevfileContentRequired(obj DevfileContent) error {
	return nil
}

// AssertRecurseDevfileContentRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DevfileContent (e.g. [][]DevfileContent), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDevfileContentRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDevfileContent, ok := obj.(DevfileContent)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDevfileContentRequired(aDevfileContent)
	})
}
