/*
 * odo dev
 *
 * API interface for 'odo dev'
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GeneralSuccess struct {
	Message string `json:"message,omitempty"`
}

// AssertGeneralSuccessRequired checks if the required fields are not zero-ed
func AssertGeneralSuccessRequired(obj GeneralSuccess) error {
	return nil
}

// AssertRecurseGeneralSuccessRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GeneralSuccess (e.g. [][]GeneralSuccess), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGeneralSuccessRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGeneralSuccess, ok := obj.(GeneralSuccess)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGeneralSuccessRequired(aGeneralSuccess)
	})
}
