/*
 * odo dev
 *
 * API interface for 'odo dev'
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DevfilePutRequest struct {
	Content string `json:"content"`
}

// AssertDevfilePutRequestRequired checks if the required fields are not zero-ed
func AssertDevfilePutRequestRequired(obj DevfilePutRequest) error {
	elements := map[string]interface{}{
		"content": obj.Content,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseDevfilePutRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DevfilePutRequest (e.g. [][]DevfilePutRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDevfilePutRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDevfilePutRequest, ok := obj.(DevfilePutRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDevfilePutRequestRequired(aDevfilePutRequest)
	})
}
