/*
 * odo dev
 *
 * API interface for 'odo dev'
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TelemetryGet200Response struct {
	Enabled bool `json:"enabled"`

	Apikey string `json:"apikey,omitempty"`

	Userid string `json:"userid,omitempty"`
}

// AssertTelemetryGet200ResponseRequired checks if the required fields are not zero-ed
func AssertTelemetryGet200ResponseRequired(obj TelemetryGet200Response) error {
	elements := map[string]interface{}{
		"enabled": obj.Enabled,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseTelemetryGet200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TelemetryGet200Response (e.g. [][]TelemetryGet200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTelemetryGet200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTelemetryGet200Response, ok := obj.(TelemetryGet200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTelemetryGet200ResponseRequired(aTelemetryGet200Response)
	})
}
