/*
 * odo dev
 *
 * API interface for 'odo dev'
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Container struct {
	Name string `json:"name,omitempty"`

	Image string `json:"image,omitempty"`

	Command []string `json:"command,omitempty"`

	Args []string `json:"args,omitempty"`

	MemoryRequest string `json:"memoryRequest,omitempty"`

	MemoryLimit string `json:"memoryLimit,omitempty"`

	CpuRequest string `json:"cpuRequest,omitempty"`

	CpuLimit string `json:"cpuLimit,omitempty"`
}

// AssertContainerRequired checks if the required fields are not zero-ed
func AssertContainerRequired(obj Container) error {
	return nil
}

// AssertRecurseContainerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Container (e.g. [][]Container), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseContainerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aContainer, ok := obj.(Container)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertContainerRequired(aContainer)
	})
}
