/*
 * odo dev
 *
 * API interface for 'odo dev'
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InstanceGet200Response struct {

	// Directory on which this 'odo dev' instance is running
	ComponentDirectory string `json:"componentDirectory,omitempty"`

	// PID of the this 'odo dev' instance.
	Pid int32 `json:"pid,omitempty"`
}

// AssertInstanceGet200ResponseRequired checks if the required fields are not zero-ed
func AssertInstanceGet200ResponseRequired(obj InstanceGet200Response) error {
	return nil
}

// AssertRecurseInstanceGet200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InstanceGet200Response (e.g. [][]InstanceGet200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInstanceGet200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInstanceGet200Response, ok := obj.(InstanceGet200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInstanceGet200ResponseRequired(aInstanceGet200Response)
	})
}
