/*
 * odo dev
 *
 * API interface for 'odo dev'
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DevstateImageImageNamePatchRequest struct {
	ImageName string `json:"imageName,omitempty"`

	Args []string `json:"args,omitempty"`

	BuildContext string `json:"buildContext,omitempty"`

	RootRequired bool `json:"rootRequired,omitempty"`

	Uri string `json:"uri,omitempty"`

	AutoBuild string `json:"autoBuild,omitempty"`
}

// AssertDevstateImageImageNamePatchRequestRequired checks if the required fields are not zero-ed
func AssertDevstateImageImageNamePatchRequestRequired(obj DevstateImageImageNamePatchRequest) error {
	return nil
}

// AssertRecurseDevstateImageImageNamePatchRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DevstateImageImageNamePatchRequest (e.g. [][]DevstateImageImageNamePatchRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDevstateImageImageNamePatchRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDevstateImageImageNamePatchRequest, ok := obj.(DevstateImageImageNamePatchRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDevstateImageImageNamePatchRequestRequired(aDevstateImageImageNamePatchRequest)
	})
}
