== Events

=== Past events

* https://www.redhat.com/en/summit[April 28-29 2020 - Red Hat Summit]
* https://www.ibm.com/events/think/[May 5-6 2020 - IBM Think Digital]

== Slack

Join us on Slack via our
https://join.slack.com/t/openshiftdo/shared_invite/enQtODUwMjIzMzE2MjYyLWM3YjlkNTViOGNjZGQ5YjFlMzc2N2RhZjVmMDQ5NWY5ZDQ3NzMzZjYxMTE1MjY5OTVmZjgxZWMyMGRmOTc4Y2I[invite
link]

* https://openshiftdo.slack.com/messages/odo-dev[odo Dev Channel] -
Discuss odo development
* https://openshiftdo.slack.com/messages/odo-users[odo Users Channel] -
Ask questions and discuss your use cases with odo

== Email list

For general help and inquiries as well as developmental discussion, we
use Google Groups as our email list.

* https://groups.google.com/forum/#!forum/odo-users[odo-users Google
group] - General help and inquiries
* https://groups.google.com/forum/#!forum/odo-dev[odo-dev Google group]
- Developmental discussion

== Issues

* If you have any issues with odo, please
https://github.com/openshift/odo/issues[file a GitHub issue]
* Documentation issues can be filed with the
https://github.com/openshift/odo/issues/new?template=Documentation.md[documentation
template]

== Public meetings

Every two weeks, we have a contributors call meeting.

Every three weeks, we have two planning calls:

* ``Sprint Planning Preparation and Issue Triage'' - on Monday
* ``Sprint Planning'' - on Wednesday

You can find the exact dates of all scheduled odo calls together with
sprint dates in the
https://calendar.google.com/calendar/embed?src=gi0s0v5ukfqkjpnn26p6va3jfc%40group.calendar.google.com[odo
calendar].

To automatically get invites to the calls, add yourself to the
https://groups.google.com/forum/#!forum/odo-dev[odo-dev Google group].

== Contributing

=== Where do I start?

odo is a complex project that touches both Kubernetes and OpenShift. We have a list of
https://github.com/openshift/odo/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22[good
first issues] to help start.

=== How do I contribute code?

Want to submit your code? Have a look at our
https://github.com/openshift/odo/blob/master/docs/dev/development.adoc[development
guide]. It goes over every aspect from submitting to writing tests.
