== Installing Service Binding Operator

This document walks you through the steps to install link:https://github.com/redhat-developer/service-binding-operator/tree/v0.3.0[Service Binding Operator v0.3.0] on OpenShift cluster and link:https://operatorhub.io/operator/service-binding-operator[Service Binding Operator v0.4.0] on Kubernetes cluster.

=== Why do I need the Service Binding Operator?

odo uses Service Binding Operator to provide the `odo link` feature which helps connect an odo component to a service or another component.

=== Installing Service Binding Operator on OpenShift

To install Service Binding Operator on OpenShift, refer link:https://www.youtube.com/watch?v=8QmewscQwHg[this video].

=== Installing Service Binding Operator on Kubernetes

To install the Operator, execute the following `kubectl` command provided on its link:https://operatorhub.io/operator/service-binding-operator[OperatorHub.io page]:
[source,sh]
----
$ kubectl create -f https://operatorhub.io/install/service-binding-operator.yaml
----

==== Making sure that Service Binding Operator installed successfully on Kubernetes

1. One way to make sure that the Operator installed properly is to verify that its link:https://kubernetes.io/docs/concepts/workloads/pods/[pod] started and is in "Running" state (note that you will have to specify the namespace where you installed Service Binding Operator in earlier step, and the pod name will be different in your setup than what's shown in below output):
+
[source,sh]
----
$ kubectl get pods --namespace operators
NAME                                        READY   STATUS     RESTARTS   AGE
service-binding-operator-6b7c654c89-rg9gq   1/1     Running    0          15m
----

1. Another aspect to check is output of below command as suggested in the Operator's installation instruction:
+
[source,sh]
----
$ kubectl get csv -n operators
----
If you see the value under `PHASE` column to be anything other than `Installing` or `Succeeded`, please take a look at the pods in `olm` namespace and ensure that the pod starting with the name `operatorhubio-catalog` is in `Running` state:
+
[source,sh]
----
$ kubectl get pods -n olm
NAME                                READY   STATUS             RESTARTS   AGE
operatorhubio-catalog-x24dq         0/1     CrashLoopBackOff   6          9m40s
----
If you see output like above where the pod is in `CrashLoopBackOff` state or any other state other than `Running`, delete the pod (note that exact name of the pod will be different on your cluster):
+
[source,sh]
----
$ kubectl delete pods -n olm operatorhubio-catalog-x24dq
----
