= Installing odo

The following section describes how to install `odo` on different platforms via CLI as well as IDEs.

= Installing the odo command-line tool (v2.0.0-beta-1)

v2.0.0-beta-1 of odo uses **devfile** as its default deployment mechanism.

== Installing odo on Linux

=== Binary installation

[source,sh]
----
  # curl -L https://github.com/openshift/odo/releases/download/v2.0.0-beta-1/odo-linux-amd64 -o /usr/local/bin/odo
  # chmod +x /usr/local/bin/odo
----

== Installing odo on macOS

=== Binary installation

[source,sh]
----
  # curl -L https://github.com/openshift/odo/releases/download/v2.0.0-beta-1/odo-darwin-amd64 -o /usr/local/bin/odo
  # chmod +x /usr/local/bin/odo
----

== Installing odo on Windows

=== Binary installation

. Download the latest link:https://github.com/openshift/odo/releases/download/v2.0.0-beta-1/odo-windows-amd64.exe[`odo.exe`] file.
. Add the location of your `odo.exe` to your `GOPATH/bin` directory.

=== Setting the `PATH` variable for Windows 10

Edit `Environment Variables` using search:

. Click *Search* and type `env` or `environment`.
. Select *Edit environment variables for your account*.
. Select *Path* from the *Variable* section and click *Edit*.
. Click *New* and type `C:\go-bin` into the field or click *Browse* and select the directory, and click *OK*.

=== Setting the `PATH` variable for Windows 7/8

The following example demonstrates how to set up a path variable. Your binaries can be located in any location, but this example uses C:\go-bin as the location.

. Create a folder at `C:\go-bin`.
. Right click *Start* and click *Control Panel*.
. Select *System and Security* and then click *System*.
. From the menu on the left, select the *Advanced systems settings* and click the *Environment Variables* button at the bottom.
. Select *Path* from the *Variable* section and click *Edit*.
. Click *New* and type `C:\go-bin` into the field or click *Browse* and select the directory, and click *OK*.

= Installing odo in Visual Studio Code (VSCode)

The https://marketplace.visualstudio.com/items?itemName=redhat.vscode-openshift-connector[OpenShift VSCode extension] uses both `odo` and the `oc` binary to interact with your Kubernetes or OpenShift cluster.

== Plugin installation

. Launch VS Code Quick Open (Ctrl+P)

. Paste the following command:
+
[source,sh]
----
  $ ext install redhat.vscode-openshift-connector
----
