= Installing odo

The following section describes how to install `odo` on different platforms via CLI as well as IDEs.

= Installing the odo CLI tool (latest)

== Installing odo on Linux

=== Binary installation

[source,sh]
----
  $ curl -L https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/odo-linux-amd64 -o /usr/local/bin/odo
  $ chmod +x /usr/local/bin/odo
----

== Installing odo on Linux on IBM Z

=== Binary installation

----
  $ curl -L https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/odo-linux-s390x -o /usr/local/bin/odo
  $ chmod +x /usr/local/bin/odo
----

== Installing odo on Linux on IBM Power

=== Binary installation

----
  $ curl -L https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/odo-linux-ppc64le -o /usr/local/bin/odo
  $ chmod +x /usr/local/bin/odo
----

== Installing odo on macOS

=== Binary installation

[source,sh]
----
  $ curl -L https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/odo-darwin-amd64 -o /usr/local/bin/odo
  $ chmod +x /usr/local/bin/odo
----

== Installing odo on Windows

=== Binary installation

. Download the latest link:https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/odo-windows-amd64.exe[`odo-windows-amd64.exe`] file.
. Rename the downloaded file to `odo.exe` and move it to a folder of your choice, for example `C:\odo`
. Add the location of your `odo.exe` to your `%PATH%`.

=== Setting the `PATH` variable for Windows 10

Edit `Environment Variables` using search:
The following examples demonstrates how to set up a path variable. Your binaries can be located in any location, but this example uses C:\odo as the location.

. Click *Search* and type `env` or `environment`.
. Select *Edit environment variables for your account*.
. Select *Path* from the *Variable* section and click *Edit*.
. Click *New* and type `C:\odo` into the field or click *Browse* and select the directory, and click *OK*.

=== Setting the `PATH` variable for Windows 7/8

. Click *Start* and in the `Search` box types `Advance System Settings`.
. Select *Advanced systems settings* and click the *Environment Variables* button at the bottom.
. Select the *Path* variable from the *System variable* section and click *Edit*.
. Scroll to the end of the *Variable Value* and add `;C:\odo` and click *OK*.
. CLick *OK* to close the *Environment Variable* dialog.
. CLick *OK* to close the *Systems Properties* dialog.

= Installing odo in Visual Studio Code (VSCode)

The https://marketplace.visualstudio.com/items?itemName=redhat.vscode-openshift-connector[OpenShift VSCode extension] uses both `odo` and the `oc` binary to interact with your Kubernetes or OpenShift cluster.

== Plugin installation

. Launch VS Code Quick Open (Ctrl+P)

. Paste the following command:
+
[source,sh]
----
  $ ext install redhat.vscode-openshift-connector
----
