== Creating and linking with Operator backed services

In this document we will go through what Operators are, how to create and delete services from the installed Operators, and how to link an odo component with an Operator backed service. We do this walking through an example Node.js application and linking it with an etcd key-value store.

NOTE: We will be updating our documentation with more examples of linking components to different kinds of Operator backed services in future.

=== Introduction to Operators

What is an Operator?

An Operator is essentially a link:https://www.openshift.com/learn/topics/operators[custom controller]. It is a method of packaging, deploying and managing a Kubernetes-native application.

With Operators, odo allows you to create a service as defined by a Custom Resource Definition (CRD).

odo utilizes Operators and link:https://operatorhub.io/[Operator Hub] in order to provide a seamless method for custom controller service installation.

[WARNING]
====
You cannot install Operators with odo on your cluster. 

To install Operators on a Kubernetes cluster, contact your cluster administrator or see the link:https://kubernetes.io/docs/concepts/extend-kubernetes/operator/[Kubernetes documentation].

To install Operators on an OpenShift cluster, contact your cluster administrator or see the link:https://docs.openshift.com/container-platform/4.6/operators/admin/olm-adding-operators-to-cluster.html[OpenShift documentation].
====

=== Deploying your first Operator

===== Prerequisites

* You must have cluster permissions to install an Operator on either link:https://docs.openshift.com/container-platform/latest/operators/olm-adding-operators-to-cluster.html[OpenShift] or link:https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/install/install.md[Kubernetes]. If you're running a link:https://minikube.sigs.k8s.io/docs/[minikube] cluster, you can refer to link:https://odo.dev/docs/operators-on-minikube[this guide] to install Operators required to run example mentioned in this document.

=== Creating a project

Create a project to keep your source code, tests, and libraries
organized in a separate single unit.

. Log in to your cluster:
+
[source,sh]
----
$ odo login -u developer -p developer
----

. Create a project:
+
[source,sh]
----
$ odo project create myproject
 ✓  Project 'myproject' is ready for use
 ✓  New project created and now using project : myproject
----

=== Installing an Operator

In our examples, we install link:https://etcd.io/[etcd], a distributed key-value store from link:https://operatorhub.io/operator/etcd[Operator Hub].

[IMPORTANT]
====
Each Operator we install refers to the built-in `metadata.annotations.alm-examples` annotation in order to correctly deploy. If the Operator does not contain the correct metadata, you will not be able to correctly deploy. For more information, see the the link:https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#crd-templates[upstream CRD documentation]. 
====


==== Kubernetes installation

For Kubernetes installation, you must need to install the Operator Lifecycle Manager and etcd Operator from the link:https://operatorhub.io/operator/etcd[etcd installation guide on Operator Hub]. You can refer to link:https://odo.dev/docs/operators-on-minikube[this document] for steps setup Operator Lifecycle Manager and etcd Operator on a link:https://minikube.sigs.k8s.io/[minikube] cluster.

==== OpenShift installation

For OpenShift installation, the etcd Operator can be installed through the link:https://docs.openshift.com/container-platform/latest/operators/olm-adding-operators-to-cluster.html[administrative console].

==== Listing all available Operators

Before deploying your first Operator, have a look at what is available:
[source,sh]
----
$ odo catalog list services
Operators available in the cluster
NAME                          CRDs
etcdoperator.v0.9.4           EtcdCluster, EtcdBackup, EtcdRestore
----

In above output, `etcdoperator.v0.9.4` is the Operator while `EtcdCluster`,
`EtcdBackup` and `EtcdRestore` are the CRDs provided by this Operator.


=== Creating an Operator backed service

In this example, we will be deploying `EtcdCluster` service from link:https://operatorhub.io/operator/etcd[etcd Operator] to an OpenShift / Kubernetes cluster. This service is provided by the Operator `etcdoperator`. Please ensure that this Operator is installed on your OpenShift / Kubernetes cluster before trying to create `EtcdCluster` service from it. If it's not installed, please install it by logging into your OpenShift / Kubernetes cluster as `kube:admin` user.

[IMPORTANT]
====
By default, the service definition is persisted in a separate file. We can use the `--inlined` flag to save it in the devfile instead.
====

. Create an `EtcdCluster` service from the `etcdoperator.v0.9.4` Operator:
+
[source,sh]
----
$ odo service create etcdoperator.v0.9.4/EtcdCluster
Successfully added service to the configuration; do 'odo push' to create service on the cluster
----

. Confirm the Operator backed service has been created:
+
[source,sh]
----
$ odo service list
NAME                   MANAGED BY ODO                    STATE        AGE
EtcdCluster/example   Yes (nodejs-myproject-api-twhk)   Not pushed   
----

. Deploy the service on the cluster
+
[source,sh]
----
$ odo push
----

. Confirm the service has been deployed:
+
[source,sh]
----
$ odo service list
NAME                   MANAGED BY ODO                    STATE     AGE
EtcdCluster/example   Yes (nodejs-myproject-api-twhk)   Pushed      8s
----

It is important to note that `EtcdBackup` and `EtcdRestore` cannot be deployed the same way as we deployed `EtcdCluster` as they require configuring other parameters in their YAML definition.

=== Deploying Operator backed service to a cluster via YAML


In this example, we will be deploying our link:https://operatorhub.io/operator/etcd[installed etcd Operator] to an OpenShift / Kubernetes cluster.

However, we will be using the YAML definition where we modify the `metadata.name` and `spec.size`.

[IMPORTANT]
====
Deploying via YAML is a **temporary** feature as we add support for link:https://github.com/openshift/odo/issues/2785[passing parameters on the command line] and link:https://github.com/openshift/odo/issues/2799[interactive mode].
====

. Retrieve the YAML output of the operator:
+
[source,shell]
----
$ odo service create etcdoperator.v0.9.4/EtcdCluster --dry-run > etcd.yaml
----

. Modify the YAML file by redefining the name and size:
+
[source,yaml]
----
apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  name: my-etcd-cluster // Change the name
spec: 
  size: 1 // Reduce the size from 3 to 1
  version: 3.2.13
----

. Create the service from the YAML file:
+
[source,shell]
----
$ odo service create --from-file etcd.yaml
----

. Confirm that the service has been created:
+
[source,shell]
----
$ odo service list
----

=== Linking an odo component with an Operator backed service

Linking a component to a service means, in simplest terms, to make a service usable from the component. odo uses link:https://github.com/redhat-developer/service-binding-operator/[Service Binding Operator] to provide the linking feature. Please refer to link:https://odo.dev/docs/install-service-binding-operator.adoc[this document] to install it on OpenShift or Kubernetes.

For example, once you link an EtcdCluster service with your Node.js application, you can use (or, interact with) the EtcdCluster from within your node app. The way odo facilitates linking is by making sure that specific environment variables from the pod in which the service is running are configured in the pod of the component as well.

After having created a service using either of the two approaches discussed above, we can now connect an odo component with the service thus created.

. Make sure you are executing the command for a component that's pushed (`odo push`) to the cluster.

. Link the component with the service:
+
[source,shell]
----
$ odo service list
NAME                           MANAGED BY ODO                    STATE     AGE
EtcdCluster/my-etcd-cluster   Yes (nodejs-myproject-api-twhk)   Pushed    17s

$ odo link EtcdCluster/example
 ✓  Successfully created link between component "node-todo" and service "EtcdCluster/example"

To apply the link, please use `odo push`

$ odo push
----

[IMPORTANT]
====
For the link between a component and Operator Hub backed service to take effect, make sure you do `odo push`. The link won't be effective otherwise. By default, the link definition is persisted in a separate file. We can use the `--inlined` flag to save it in the devfile instead.
====

=== Unlinking an odo component from an Operator backed service

Unlinking unsets the environment variables that were set by linking. This would cause your application to cease being able to communicate with the service linked using `odo link`.

IMPORTANT: `odo unlink` doesn't work on a cluster other than OpenShift (that is, minikube, or vanilla Kubernetes, etc.) because Service Binding Operator cannot be setup the OLM way (that is, we cannot list it by doing `odo catalog list services` or `kubectl get csv` like we can do for etcd Operator in this document). We are link:https://github.com/redhat-developer/service-binding-operator/issues/623[working making this possible].

. Make sure you are executing the command for a component that's pushed (`odo push`) to the cluster.

. Unlink the component from the service it is connected to:
+
[source,shell]
----
$ odo unlink EtcdCluster/example
✓  Successfully unlinked component "node-todo" from service "EtcdCluster/example"

To apply the changes, please use `odo push`

$ odo push
----

[IMPORTANT]
====
For unlinking to take effect, make sure you do `odo push`. It won't be effective otherwise.
====

=== Deleting an Operator backed service

To delete an Operator backed service, provide full name of the service that you see in the output of `odo service list`. For example:

[source,shell]
----
$ odo service list
NAME                           MANAGED BY ODO                    STATE     AGE
EtcdCluster/my-etcd-cluster   Yes (nodejs-myproject-api-twhk)   Pushed    3m11s

$ odo service delete EtcdCluster/example
----

To forcefully delete a service without being prompted for confirmation, use the `-f` flag like below:

[source,shell]
----
$ odo service delete EtcdCluster/example -f
----

Confirm that the service has been deleted from the devfile:

[source,shell]
----
$ odo service list
NAME                           MANAGED BY ODO                    STATE             AGE
EtcdCluster/my-etcd-cluster   Yes (nodejs-myproject-api-twhk)   Deleted locally   3m26s
----

Undeploy the service from the cluster and verify it has been undeployed:

[source,shell]
----
$ odo push
$ odo service list 
 ✗  no operator backed services found in namespace: myproject
----
