== Introduction to secure devfile registry

**What is a secure devfile registry?**

A secure devfile registry is a devfile registry that a user can only access using credentials.

**Where to host secure devfile registry?**

A user can host a secure devfile registry on a private GitHub repository or an enterprise GitHub repository.

== Adding a secure devfile registry on a GitHub repository

. Creating new GitHub repository to host the secure devfile registry:
+
Please https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-new-repository[create a new private or enterprise GitHub repository] and push the devfile registry to the created repository. The sample GitHub-hosted devfile registry can be found https://github.com/odo-devfiles/registry/[here].

. Creating a personal access token to access the secure devfile registry
+
Please https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token[create a personal access token], select `repo` as token scope.

. Keyring setup
+
There is no specific keyring setup for secure devfile registry, you only need to ensure the keyring which is working properly on your system, if you hit issues please follow the below instructions to troubleshoot the issues of your keyring with respect to the corresponding platforms.

- https://support.apple.com/en-ca/guide/keychain-access/welcome/mac[Mac keychain]
- https://nurdletech.com/linux-notes/agents/keyring.html[GNOME keyring setup on RedHat Enterprise Linux]
- https://howtoinstall.co/en/ubuntu/xenial/gnome-keyring[GNOME keyring setup on Ubuntu Linux]
- https://help.gnome.org/users/seahorse/stable/index.html.en[Linux GNOME keyring]
- https://support.microsoft.com/en-ca/help/4026814/windows-accessing-credential-manager[Windows credential manager]

. Adding secure devfile registry
+
Please run `odo registry add <registry name> <registry URL> --token <token>` to add the secure devfile registry to odo, for more registry related commands please refer to `odo registry --help`.

- <registry name>: user-defined devfile registry name.
- <registry URL>: the URL of GitHub repository that you create on step 1.
- <token>: the personal access token that you created on step 2.

== Steps for setting up a secure starter project on a GitHub repository

. Creating a new GitHub repository to host the secure starter project
+
* Please https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-new-repository[create a new private or enterprise GitHub repository] and push the starter project to the created repository. The sample GitHub-hosted starter project can be found https://github.com/odo-devfiles/nodejs-ex[here].
* Ensure the `starterProjects` section in the corresponding devfile of your secure devfile registry links to the secure starter project, for example:
+
```
starterProjects:
  - name: nodejs-starter
    git:
      remotes:
        origin: "<secure starter project link>"
```

. Creating a personal access token to access the secure starter project
+
Please https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token[create a personal access token], select `repo` as token scope.

. Creating a devfile component from the secure devfile registry and downloading the secure starter project
+
Please run `odo create nodejs --registry <registry name> --starter --starter-token <starter project token>`

- <registry name>: user-defined devfile registry name.
- <starter project token>: the personal access token that you create on step 2.

NOTE: GitHub only supports user-scoped personal access tokens. If the repository that hosts the secure registry and the repository that hosts the secure starter project are created under the same GitHub user, then the token can be used for both downloading the devfile and starter project. For that case you don't need to explicitly pass in the flag `--starter-token <starter project token>`, odo can automatically use one token to download both devfile and starter project.
