== Storage

`odo` lets users manage storage volumes in the cluster. A storage volume is a https://kubernetes.io/docs/concepts/storage/volumes/#persistentvolumeclaim[PVC], which is a way for users to "claim" durable storage (such as a GCE PersistentDisk or an iSCSI volume) without knowing the details of the particular cloud environment. The storage volume can be used to persist data across restarts and rebuilds of the component.

== Adding a storage volume

We can add a storage volume to the cluster using `odo storage create`

[source,sh]
----
  $ odo storage create store --path /data --size 1Gi
   ✓  Added storage store to nodejs-project-ufyy

  Please use `odo push` command to make the storage accessible to the component
----
The storage volume in the above example has been mounted to the `/data` path and has a size of `1Gi`

== Listing storage volumes

We can check the storage volumes currently used by the component using `odo storage list`

[source,sh]
----
  $ odo storage list
  The component 'nodejs-project-ufyy' has the following storage attached:
  NAME      SIZE     PATH      STATE
  store     1Gi      /data     Not Pushed
----

== Deleting a storage volume

We can delete a storage volume using `odo storage delete`

[source,sh]
----
  $ odo storage delete store -f
  Deleted storage store from nodejs-project-ufyy

  Please use `odo push` command to delete the storage from the cluster
----

== Adding storage to specific container

If your devfile has multiple containers, you can specify to which container you want the
storage to attach to using `--container` flag in the `odo storage create` command.

For example:

Let us take a devfile with multiple containers that looks like (partial excerpt):

[source, yaml]
----
...
components:
  - name: runtime
    container:
      image: registry.access.redhat.com/ubi8/nodejs-12:1-36
      memoryLimit: 1024Mi
      endpoints:
        - name: "3000-tcp"
          targetPort: 3000
      mountSources: true
  - name: funtime
    container:
      image: registry.access.redhat.com/ubi8/nodejs-12:1-36
      memoryLimit: 1024Mi

...
----

Here, we have 2 containers, with names `runtime` and `funtime`. To attach a storage, only to the `funtime` container, we can do

[source, sh]
----
  $ odo storage create store --path /data --size 1Gi --container funtime
   ✓  Added storage store to nodejs-testing-xnfg

  Please use `odo push` command to make the storage accessible to the component

----

You can list the same, using `odo stprage list` command

[source, sh]
----
  $ odo storage list
  The component 'nodejs-testing-xnfg' has the following storage attached:
  NAME      SIZE     PATH      CONTAINER     STATE
  store     1Gi      /data     funtime       Not Pushed

----