/**
 * odo dev
 * API interface for \'odo dev\'
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DevstateCommandCommandNameMovePostRequest { 
    /**
     * Initial group of the command
     */
    fromGroup?: string;
    /**
     * Initial index of the command in the group
     */
    fromIndex?: number;
    /**
     * Target group of the command
     */
    toGroup?: string;
    /**
     * Target index of the command in the group
     */
    toIndex?: number;
}

