apiVersion: v1 
kind: Namespace 
metadata: 
  name: my-postgresql-operator-dev4devs-com 
--- 
apiVersion: operators.coreos.com/v1 
kind: OperatorGroup 
metadata: 
  name: operatorgroup 
  namespace: my-postgresql-operator-dev4devs-com 
spec: 
  targetNamespaces: 
  - my-postgresql-operator-dev4devs-com 
--- 
apiVersion: operators.coreos.com/v1alpha1 
kind: Subscription 
metadata: 
  name: my-postgresql-operator-dev4devs-com 
  namespace: my-postgresql-operator-dev4devs-com 
spec: 
  channel: alpha 
  name: postgresql-operator-dev4devs-com 
  source: operator-ibm-catalog
  sourceNamespace: openshift-marketplace