= ci-reference

== Running integration test job in Travis CI

For default oc, use the configuration in `.travis.yaml`. For example:

[source,sh]
----
  # Run main e2e tests
    - <<: *base-test
      stage: test
      name: "Main e2e tests"
      script:
        - ./scripts/oc-cluster.sh
        - make bin
        - sudo cp odo /usr/bin
        - oc login -u developer
        - make test-main-e2e
----

If you need to run `odo` integration tests against a specific version of Openshift, use env variable `OPENSHIFT_CLIENT_BINARY_URL` to pass the https://github.com/openshift/origin/releases[released] oc client URL in `.travis.yaml`. For oc v3.10.0, use the configuration:

[source,sh]
----
  # Run main e2e tests
    - <<: *base-test
      stage: test
      name: "Main e2e tests"
      script:
        - OPENSHIFT_CLIENT_BINARY_URL=https://github.com/openshift/origin/releases/download/v3.10.0/openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit.tar.gz ./scripts/oc-cluster.sh
        - make bin
        - sudo cp odo /usr/bin
        - oc login -u developer
        - make test-main-e2e
----

== Running integration tests on Prow

Prow is the Kubernetes or OpenShift way of managing workflow, including tests. Odo integration and periodic test targets are passed through the script scripts/openshiftci-presubmit-all-tests.sh and scripts/openshiftci-periodic-tests.sh respectively available in the https://github.com/openshift/odo/tree/master/scripts[odo] repository. Prow uses the script through the command attribute of the odo job configuration file in https://github.com/openshift/release/tree/master/ci-operator/config/openshift/odo[openshift/release] repository.

For running integration test on 4.x cluster, job configuration file will be
[source,sh]
----
    tests:
    - as: integration-e2e
      commands: scripts/openshiftci-presubmit-all-tests.sh
      openshift_installer_src:
       cluster_profile: aws
      secret:
       mount_path: /tmp/secret
       name: odo-secret
----

Similarly for running periodic test on 4.x cluster, job configuration file will be
[source,sh]
----
    tests:
    - as: integration-e2e
      commands: scripts/openshiftci-periodic-tests.sh
      openshift_installer_src:
       cluster_profile: aws
      secret:
       mount_path: /tmp/secret
       name: odo-secret
----

To generate the odo job file, run `make jobs` in https://github.com/openshift/release[openshift/release] for the odo pr and periodic tests.

Job dashboard is monitored at:

* link:https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/?repo=openshift%2Fodo[odo pr jobs dashboard]
* link:https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/?type=periodic&job=periodic-\*odo*[odo periodic jobs dashboard]
