= Development Guide
:toc: macro
:toc-title:
:toclevels: 1

toc::[]

== Setting up

Requires *Go 1.15*

Testing and release builds happen with the above version. Developers are advised to stick to this version if they can but it is not compulsory.


[WARNING]
====
If you are adding any features that require a higher version of golang, than the one mentioned above, please contact the maintainers in order to check if the releasing systems can handle the newer version. If that is ok, please ensure you update the required golang version, both here and in the files below, in your PR.

.List of files to update for golang version
 * link:/scripts/rpm-prepare.sh[`scripts/rpm-prepare.sh`]
 * link:/Dockerfile.rhel[`Dockerfile.rhel`]
 * link:/openshift-ci/build-root/Dockerfile[`openshift-ci/build-root/Dockerfile`]
====

First setup your fork of the odo project, following the steps below

 . link:https://help.github.com/en/articles/fork-a-repo[Fork] the link:https://github.com/openshift/odo[`odo`] repository.

 . Clone your fork:
+
NOTE: odo uses `go modules` to manage dependencies which means you can clone the code anywhere you like but for backwards compatibility
we would be cloning it under `$GOPATH`
+

----
$ git clone https://github.com/<YOUR_GITHUB_USERNAME>/odo.git $GOPATH/src/github.com/openshift/odo
$ cd $GOPATH/src/github.com/openshift/odo
$ git remote add upstream 'https://github.com/openshift/odo'
----
+
When cloning `odo`, the Windows terminal such as PowerShell or CMD may throw a *Filename too long* error. To avoid such an error, set your Git configuration as follows:
+
----
$ git config --system core.longpaths true
----

 . Install tools used by the build and test system:
+
----
$ make goget-tools
----

== Submitting a pull request(PR)

 . Create a branch, refer to the guidelines below in the sections below, and create a PR with your changes. If your PR is still in-progress, indicate this with a label or add WIP in your PR title.
+
A PR must include:

 * Descriptive context that outlines what has been changed and why
 * A link to the active or open issue it fixes (if applicable)
 * (OPTIONAL) A "signed-off" signature is good practice. You may sign your commit using `git commit -s` or `git commit --amend --no-edit -s` to a previously created commit

== Useful make targets

bin:: (default) `go build` the executable in cmd/odo
install:: build and install `odo` in your GOPATH
validate:: run gofmt, go vet and other validity checks
goget-tools:: download tools used to build & test
test:: run all unit tests - same as `go test pkg/\...`
test-integration:: run all integration tests
test-coverage:: generate test coverage report

Read the Makefile itself for more information.


== Reviewing a PR

=== PR review process

. Once you submit a PR, the @openshift-ci-robot automatically requests two reviews from reviewers and suggests an approver based on `OWNERS` files.
. Each PR requires *one* code review (lgtm label) and *one* approve (approved label).
. After a code reviewer is satisfied with the changes s/he adds `/lgtm` (looks good to me) as a comment to the PR. Which applies the *lgtm* label.
. The approver reviews the PR and if satisfied, adds `/approve` as a comment to the PR. Which applies the *approve* label.
* After the PR has *lgtm* and *approve* labels and the required tests pass, the bot automatically merges the PR.
+
NOTE: If you are a maintainer and have write access to the `odo` repository, modify your git configuration so that you do not accidentally push to upstream:
+
----
$ git remote set-url --push upstream no_push
----

=== What to look out for when reviewing a pull request:

* Have tests been added?
* Does the feature or fix work locally?
* Is the code understandable, have comments been added to the code?
* A PR should pass all the pre-submit tests, all request changes must be resolved, and needs at least two approving reviews. If you apply the `/lgtm` label before it meets this criteria, put it on hold with the `/hold` label immediately. You can use `/lgtm cancel` to cancel your `/lgtm` and use `/hold cancel` once you are ready to approve it. This especially applies to draft PRs.
* Approvers can use `/approve` and `/approve cancel` to approve or hold their approval respectively.

=== About Prow
`odo` uses the link:https://github.com/kubernetes/test-infra/tree/master/prow[Prow] infrastucture for CI testing.

* It uses link:https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md[OWNERS] files to determine who can approve and lgtm a PR.
* Prow has two levels of OWNERS, *Approvers* and *Reviewers*
** *Approvers* look for holistic acceptance criteria, including
dependencies with other features, forward and backward compatibility, API and flag definitions, etc. In essence, the high levels of design
** *Reviewers* look for general code quality, correctness, sane software engineering, style, etc. In essence, the quality of the actual code itself.

* Avoid merging the PR manually (unless it is an emergency and  you have the required permissions). Prow’s tide component automatically merges the PR once all the conditions are met.
It also ensures that post-submit tests (tests that run before merge) validate the PR.
* Use the link:https://prow.ci.openshift.org/command-help[command-help] to see the list of possible bot commands.

=== Setting custom Init Container image for bootstrapping Supervisord
For quick deployment of components, odo uses the link:https://github.com/ochinchina/supervisord[Supervisord] process manager.
Supervisord is deployed via link:https://docs.openshift.com/container-platform/4.1/nodes/containers/nodes-containers-init.html[Init Container] image. 

`ODO_BOOTSTRAPPER_IMAGE` is an environmental variable which specifies the Init Container image used for Supervisord deployment.  You can modify the value of the variable to use a custom Init Container image.
The default Init Container image is `quay.io/openshiftdo/init` 

. To set a custom Init Container image, run:
+
----
ODO_BOOTSTRAPPER_IMAGE=quay.io/myrepo/myimage:test
----

. To revert back to the default Init Container image, unset the variable:
+
----
unset ODO_BOOTSTRAPPER_IMAGE
----

== Dependency management

`odo` uses `go mod` to manage dependencies. 

`odo` uses `go mod` with vendor directory.
This means that you should use `-mod=vendor` flag with all `go` commands. Or use `GOFLAGS` to set it permanently (`export GOFLAGS=-mod=vendor`).
Vendor is important to make sure that odo can always be built even offline.


=== Adding a new dependency

. Just add new `import` to your code
+
NOTE:  If you want to use a specific version of a module you can do `go get <pkg>@<version>`, for example (`go get golang.org/x/text@v0.3.2`)
+
. Run `go mod tidy` and `go mod vendor`.
. Commit the updated `go.mod`, `go.sum` and `vendor` files to git.

== Release guide

=== Releasing a new version

Making artifacts for a new release is automated within RedHat's internal CI servers. Contact a maintainer for the internal link to release a new version of odo.

To release a new version on GitHub:

**Create a PR that:**

* Updates the version in the following files:

** link:/pkg/version/version.go[`pkg/version/version.go`]
** link:/Dockerfile.rhel[`Dockerfile.rhel`]
** link:/scripts/rpm-prepare.sh[`scripts/rpm-prepare.sh`]

There is a helper script link:/scripts/bump-version.sh[scripts/bump-version.sh] that changes version number in all the files listed above.

Also, ensure you add the next version on top of the current one in the link:/Changelog.md['Changelog.md'] so that it is clear that future changelog updates happen under next version.

. Merge the above PR.
. Once the PR is merged create and push the new git tag for the version.
. Create a new release using the GitHub site (this must be a proper release and NOT a draft).
+

. Update the release description (changelog) on GitHub. Run the script below to get the baseline template of release changelog and then copy and paste the content from the link:/Changelog.md['Changelog.md'] into appropriately marked location in generated `/tmp/changelog.md`.
+
----
$ export GITHUB_TOKEN=yoursupersecretgithubtoken
$ ./scripts/changelog-script.sh ${PREVIOUS_VERSION} ${NEW_VERSION}
----
. Update the Homebrew package:
.. Check commit id for the released tag `git show-ref v0.0.1`
.. Create a PR to update `:tag` and `:revision` in the https://github.com/kadel/homebrew-odo/blob/master/Formula/odo.rb[`odo.rb`] file
in https://github.com/kadel/homebrew-odo[`kadel/homebrew-odo`].
. Create a PR and update the file `build/VERSION` with the  latest version number.
. Create a blog post! Follow the https://github.com/openshift/odo/tree/main/docs/blog[template.md] file and push it to the website (a tutorial is located on the https://github.com/openshift/odo/tree/gh-pages[gh-pages] branch of odo
. After the blog post, ideally the CHANGELOG in the release should be the same as the blog post. This is an example of a good release changelog: https://github.com/openshift/odo/releases/tag/v2.0.0
. Add the built site (including the blog post) to the release with `site.tar.gz` using the  https://github.com/openshift/odo/tree/gh-pages#bundling-the-site-for-releases[bundling the site for releases] guide.

== Writing machine readable output code

Here are some tips to consider when writing machine-readable output code.

- Match similar Kubernetes / OpenShift API structures
- Put as much information as possible within `Spec`
- Use `json:"foobar"` within structs to rename the variables 


Within odo, we unmarshal all information from a struct to json. Within this struct, we use `TypeMeta` and `ObjectMeta` in order to supply meta-data information coming from Kubernetes / OpenShift. 

Below is working example of how we would implement a "GenericSuccess" struct.


[source,go]
----
  package main
  
  import (
    "encoding/json"
    "fmt"
  
    metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
  )
  
  // Create the struct. Here we use TypeMeta and ObjectMeta
  // as required to create a "Kubernetes-like" API.
  type GenericSuccess struct {
    metav1.TypeMeta   `json:",inline"`
    metav1.ObjectMeta `json:"metadata,omitempty"`
    Message           string `json:"message"`
  }
  
  func main() {
  
    // Create the actual struct that we will use
    // you will see that we supply a "Kind" and
    // APIVersion. Name your "Kind" to what you are implementing
    machineOutput := GenericSuccess{
      TypeMeta: metav1.TypeMeta{
        Kind:       "genericsuccess",
        APIVersion: "odo.dev/v1alpha1",
      }, 
      ObjectMeta: metav1.ObjectMeta{
        Name: "MyProject",
      }, 
      Message: "Hello API!",
    }
  
    // We then marshal the output and print it out
    printableOutput, _ := json.Marshal(machineOutput)
    fmt.Println(string(printableOutput))
  }
----

== odo-bot

https://github.com/odo-bot[odo-bot] is the GitHub user that provides automation for certain tasks in `odo`.

It uses the `.travis.yml` script to upload binaries to the GitHub release page using the *deploy-github-release*
personal access token.

== Licenses

`odo` uses link:https://github.com/frapposelli/wwhrd[wwhrd] to  check license compatibility of vendor packages. The configuration for `wwhrd` is stored in link:https://github.com/openshift/odo/blob/main/.wwhrd.yml[`.wwhrd.yml`].

The `whitelist` section is for licenses that are always allowed. The `blacklist` section is for licenses that are never allowed and will always fail a build. Any licenses that are not explicitly mentioned come under the `exceptions` section and need to be explicitly allowed by adding the import path to the exceptions.

More details about the license compatibility check tool can be found https://github.com/frapposelli/wwhrd[here]
