= Logging in `odo`

https://godoc.org/k8s.io/klog[Glog] is used for V style logging in `odo`.

== Working

Every `odo` command takes an optional flag `-v` that must be used with an integer log level in the range from 0-9. Any INFO severity log statement that is logged at a level lesser than or equal to the one passed with the command alongside `-v` flag will be logged to STDOUT.

Alternatively, enviroment variable `ODO_LOG_LEVEL` can be used to set the verbosity of the log level in the integer range 0-9. The value set by `ODO_LOG_LEVEL` can be overridden by explicitly passing the `-v` command line flag to the `odo` command, in such an event `-v` flag takes precedence over the enviroment variable `ODO_LOG_LEVEL`.

All ERROR severity level log messages will always be logged regardless of the values of `v` or `ODO_LOG_LEVEL`.

== Usage

Every source file that requires logging will need to import glog:

----
$ import "k8s.io/klog"
----

Any default debug level severity messages need to be logged using:

----
$ klog.V(4).Infof(msg, args...)`
----

For more information on level logging conventions please refer
link:https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-output-verbosity-and-debugging[here].

Error messages can be logged as under:

----
$ klog.Errorf(msg, args...)
----

Warning messages can be logged as under:

----
$ klog.Warningf(msg, args...)
----

In addition to the above logging, the following hidden flags are available for debugging:

----
      --alsologtostderr                  log to standard error as well as files
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files (default false)
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs. Level varies from 0 to 9 (default 0).
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
----
