= ci-reference

== Running integration test job in Travis CI

For default oc, use the configuration in `.travis.yaml`. For example:

[source,sh]
----
  # Run main e2e tests
    - <<: *base-test
      stage: test
      name: "Main e2e tests"
      script:
        - ./scripts/oc-cluster.sh
        - make bin
        - sudo cp odo /usr/bin
        - oc login -u developer
        - make test-main-e2e
----

If you need to run `odo` integration tests against a specific version of Openshift, use env variable `OPENSHIFT_CLIENT_BINARY_URL` to pass the https://github.com/openshift/origin/releases[released] oc client URL in `.travis.yaml`. For oc v3.10.0, use the configuration:

[source,sh]
----
  # Run main e2e tests
    - <<: *base-test
      stage: test
      name: "Main e2e tests"
      script:
        - OPENSHIFT_CLIENT_BINARY_URL=https://github.com/openshift/origin/releases/download/v3.10.0/openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit.tar.gz ./scripts/oc-cluster.sh
        - make bin
        - sudo cp odo /usr/bin
        - oc login -u developer
        - make test-main-e2e
----

== Running integration tests on Prow

Prow is the Kubernetes or OpenShift way of managing workflow, including tests. To get tests, you need to raise PR to `openshift/release` repository setting up appropriate ci operator config and job files. Reference for the same is available in the repository.

Note that prow gives you a bare bones cluster, so we need to pre-configure the same so that the cluster is in state expected such as auth being configured and so on.

You can do this by running `$ make configure-installer-tests-cluster` before running actual tests. This script is configurable with environment variables as:

* `CI`: If this environment is set, then initial setup is skipped in favor of only configuring authentication. Use this only with OpenShift CI.
* `DEFAULT_INSTALLER_ASSETS_DIR`: The location where OpenShift installer creates assets such as kube admin password and the kubeconfig file.
