package logs

import "io"

type Client interface {
	// GetLogsForMode gets logs of the containers for the specified mode (Dev, Deploy or both) of the provided
	// component name and namespace. It returns a slice of maps where container name is the key and its logs are
	// the value. Each map is a key-value pair of container name and its logs for a specific pod. Setting follow boolean
	// to true helps follow/tail the logs of the pods.
	// The accepted values for mode are ComponentDevMode, ComponentDeployMode and ComponentAnyMode
	// found in the pkg/labels package.
	// out is the Writer to which any logs generated by odo (for example, errors) will be printed
	// logChan is the channel on which the logs of the Pods will be put to be able to start printing logs as soon as
	// Pods in specified mode are found
	// doneChan is used to indicate that logs of the pods have been grabbed from server
	GetLogsForMode(
		mode string,
		componentName string,
		namespace string,
		follow bool,
		out io.Writer,
		logChan chan map[string]interface{},
		doneChan chan struct{},
	) error
}
